### ISSUE TITLE
Window Layout Mode: Space misbehaves on multi monitor setup

### ISSUE THREAD

**Issue by sonnius** [jasonrudolph/keyboard#18]
When using "Window Layout Mode: Space" on a multimonitor setup the window always moves to the laptop screen instead of the active screen.

**Comment by jasonrudolph** [comment]
@sonnius: This should be resolved by 2b73fc301629dfc9664428f654fdd67944aa5579. If you continue to see this issue, please let me know. Thanks for reporting this! :bow:
