### ISSUE TITLE
How to use (S)uper (D)uper Mode?

### ISSUE THREAD

**Issue by piotryordanov** [jasonrudolph/keyboard#22]
I'm confused as to how to use the (S)uper (D)uper Mode.
I press both "s" and "d" keys together, but nothing happens.

How should I do it?

Thx!

**Comment by willmcclellan** [comment]
@piotryordanov you have to keep them held down and once you do that you'll get a notice in the bottom right corner of the screen that you're in super duper mode

**Comment by cbrwizard** [comment]
Had the same issue, restarting mac after installation helped
