### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by peng051410** [jasonrudolph/keyboard#29]
When i run 'script/setup', I got the message:
```
script/setup
The Brewfile's dependencies are satisfied.
ln: /Users/zmm/.config//karabiner: Operation not permitted
```
My soft info:
macOS Sierra 10.12.5 (16F73)
Hammerspoon 0.9.55 (0.9.55)
Karabiner-Elements 0.91.12

**Comment by tgturner** [comment]
@peng051410 Ran into the same probably today. Was able to solve it by removing the existing `~/.config/karabiner` folder.

**Comment by piggyslasher** [comment]
Yup. That's what it was. I think we can close this.

**Comment by peng051410** [comment]
Yes，it works for me!Thanks!
