### ISSUE TITLE
Vim replacement?

### ISSUE THREAD

**Issue by cwagner22** [jasonrudolph/keyboard#34]
I was starting to learn vim before discovering the (S)uper (D)uper Mode. I'm curious if you think it's still worth it to use vim or not, so far I really like your mode and am probably gonna use it instead.

**Comment by jasonrudolph** [comment]
> I'm curious if you think it's still worth it to use vim or not ...

That's a very personal choice. 😇  There are probably as many opinions on that matter as their are programmers. 😬 

With that in mind, I can only offer [my personal opinion](https://github.com/jasonrudolph/keyboard/tree/f76f389d1667fa3767aad50cf658c6cce22fcaf1#more-useful-for-me). Personally, I use [Atom](https://atom.io/) as my primary editor, and I use [(S)uper (D)uper Mode](https://github.com/jasonrudolph/keyboard/tree/f76f389d1667fa3767aad50cf658c6cce22fcaf1#super-duper-mode)'s vim keys to navigate left/down/up/right in Atom and in every other app on my Mac. As [noted in the README](https://github.com/jasonrudolph/keyboard/tree/f76f389d1667fa3767aad50cf658c6cce22fcaf1#toward-a-more-useful-keyboard), I value that consistency:

> I want the _same_ (more useful) keyboard in every app.
> Ubiquitous keyboarding.
> Muscle memory.
> [Don't make me think][don't-make-me-think].
>
> How do I go to the beginning of the line in this app?
> The same way I go to the beginning of the line in _every_ app!
> Don't make me think.
>
> How do I go to the top of the file/screen/page in this app?
> The same way I...
> Well, you get the point.

:smile:

That said, for those times when I'm ssh'ed into a server, and there's no Atom in sight, I find it valuable to be able to get around and perform basic editing in vim. Vim is definitely my preferred *terminal-based* editor.

I hope this helps.

[don't-make-me-think]: http://en.wikipedia.org/wiki/Don't_Make_Me_Think
