### ISSUE TITLE
stuck on Tapping caskroom/cask

### ISSUE THREAD

**Issue by imagnma** [jasonrudolph/keyboard#45]
Hello there, can't wait to adabting this keyboard 

so I followed the insteractions and after running `script/setup` i'm left out with the following : 
```
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
```
when I run brew bundle install it get stuck on 
```
Tapping caskroom/cask
Using karabiner-elements
```

now when I redo script/setup i get 

```
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
Tapping caskroom/cask
Using karabiner-elements
```

thanks

**Comment by jasonrudolph** [comment]
:wave: @imagnma: Sorry you're running into trouble getting started. 

If you run `brew cask list`, do you see `hammerspoon` and `karabiner-elements` in the output?

**Comment by imagnma** [comment]
Oh, you are so kind, I've run it and I got back : 
```
Cannot read termcap database;
using dumb terminal settings.
karabiner-elements
```
hmm, why it isn't showing hammerspoon ?

**Comment by imagnma** [comment]
the downloading speed of cask is horablie slow, so I downlod i drag to /application
now :  
```
ln: /Users/im/.config//karabiner: Operation not permitted
```
with and without sudo, same message

**Comment by imagnma** [comment]
should I manually add karabiner.json to ~/.confg/karabiner then comment the `ln` line ?

**Comment by jasonrudolph** [comment]
> the downloading speed of cask is horablie slow,

Oh. I'm guessing that's why you were getting stuck here earlier:

>> when I run brew bundle install it get stuck on
>> 
>> ```
>> Tapping caskroom/cask
>> Using karabiner-elements
>> ```

Regarding the new error you're seeing:

> `ln: /Users/im/.config//karabiner: Operation not permitted`

It seems like you already have an existing configuration folder for karabiner at `/Users/im/.config/karabiner`. You'll need to move, remove, or change the name of that folder and then run `script/setup` again.

**Comment by imagnma** [comment]
great, now finally something happend

**Comment by imagnma** [comment]
both apps opend

**Comment by imagnma** [comment]
thank you very much, I'm going to test it now
