### ISSUE TITLE
Installing with both homebrew and fink installed

### ISSUE THREAD

**Issue by dnstarostin** [jasonrudolph/keyboard#58]
> .keyboard%:script/setup
> /sw/bin/which: illegal option -- s
> Usage: /sw/bin/which [-a] args
> Homebrew is required: http://brew.sh/

How to I point the installation script to the Homebrew installation?

**Comment by jasonrudolph** [comment]
> How to I point the installation script to the Homebrew installation?

:wave: Hi @dnstarostin: I've never seen this problem before, so I'm not exactly sure how to resolve it, but I can offer a potential workaround. I think you can _probably_ get around this issue as follows:

1. Using your existing Homebrew installation, manually run the brew commands that are present in [`Brewfile`](https://github.com/jasonrudolph/keyboard/blob/ddffacf80f57b74965294e91ec2a18d527b97956/Brewfile)
2. Comment out the [Homebrew-related lines in `script/setup`](https://github.com/jasonrudolph/keyboard/blob/ddffacf80f57b74965294e91ec2a18d527b97956/script/setup#L5-L7)
3. Run `script/setup`

I think that will do the trick. I hope this helps.

**Comment by dnstarostin** [comment]
Thank you!!!

This (is the workaround I found: instead of standalone Hammerspoon I
installed it via 'brew install cask'. This way some problems disappeared. I
have not tested further since it is working now.
