### ISSUE TITLE
How to switch the Case?

### ISSUE THREAD

**Issue by aantipov** [jasonrudolph/keyboard#64]
After remapping the `Caps Lock`, I'm not able to switch the case now, I need to always hold down `Shift` button if I need to type in upper case.

How can I define another key combination (say `Shift-Caps_Lock`) to do case-switching?

**Comment by jasonrudolph** [comment]
:wave: @aantipov: I think you can implement something like this using Karabiner-Elements. For example, https://github.com/pqrs-org/Karabiner-Elements/issues/346#issuecomment-463258397 describes a configuration for double-tapping <kbd>shift</kbd> to enable caps lock.

I don't personally find myself wanting to enable caps lock, so it's unlikely that I'd add this to jasonrudolph/keyboard, but I hope the pointer above is helpful.

**Comment by aantipov** [comment]
@jasonrudolph thanks a lot for the prompt answer. That works for me, I like it, awesome!

**Comment by narze** [comment]
Some ideas to trigger capslock :
- Left shift + Right shift simultaneously
- Hold shift
- Double tap shift
- Shift + capslock
