### ISSUE TITLE
ln error during script/setup

### ISSUE THREAD

**Issue by harmtemolder** [jasonrudolph/keyboard#67]
Running `script/setup` gives me this error:
`ln: /Users/harmtemolder/.config//karabiner: Operation not permitted`
Rewriting line 12 from
`ln -sfn $PWD/karabiner ~/.config/`
to
`ln -sfn $PWD/karabiner ~/.config`
fixed this.

I'm not confident enough around `ln` to change the file, but happy to do so if you agree that this would improve it.

**Comment by jasonrudolph** [comment]
👋 @harmtemolder: Sorry you ran into this issue getting things set up. I tried to reproduce this issue locally using a fresh installation of macOS Catalina, but I wasn't able to reproduce it:

```
$ git clone https://github.com/jasonrudolph/keyboard.git ~/.keyboard
Cloning into '/Users/j/.keyboard'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 1333 (delta 5), reused 12 (delta 4), pack-reused 1317
Receiving objects: 100% (1333/1333), 3.23 MiB | 9.91 MiB/s, done.
Resolving deltas: 100% (757/757), done.

$ cd ~/.keyboard

$ script/setup
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 4610 (delta 39), reused 55 (delta 26), pack-reused 4502
Receiving objects: 100% (4610/4610), 1.00 MiB | 5.70 MiB/s, done.
Resolving deltas: 100% (2680/2680), done.
Tapped 1 command (104 files, 1.3MB).
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
Password:
Installing karabiner-elements
Installing hammerspoon
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
No matching processes belonging to you were found
Done! Remember to enable Accessibility for Hammerspoon.
```

So, I'm not sure what went wrong. :-/ 

Are things working for you now?

**Comment by harmtemolder** [comment]
Hm, that's weird. I'm on Catalina too and cannot imagine that my `ln` functions differently from yours. Ah well, removing the `/` worked for me. If you did not have to do this, then I guess there is no need to change the file.

**Comment by paulkre** [comment]
I'm on OSX Big Sur and I have the same problem. Unfortunately, removing the `/` did not fix the error.

**Comment by paulkre** [comment]
The problem was that the `~/.config/karabiner` directory already existed. The setup script worked after I removed the existing karabiner configuration (`rm -rf ~/.config/karabiner`).
