### ISSUE TITLE
Mac Big Sur - 2 Brewfile dependencies failed to install.

### ISSUE THREAD

**Issue by capnahab** [jasonrudolph/keyboard#74]
I am not sure if this is related to big Sur or not. I am running brew under Rosetta2  otherwise there is no brew with Big  Sur yet. I am using the recommended installation and with pre-installed hammerspoon and Karabiner elements brew fails to recognise the installations. If I delete the installations i get the error below, - still fialing to install the dependencies. 
Is this a Big Sur/Rosetta issue?.

❯ script/setup
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
Error: Cask 'karabiner-elements' is unavailable: No Cask with this name exists.
Installing karabiner-elements has failed!
Error: Cask 'hammerspoon' is unavailable: No Cask with this name exists.
Installing hammerspoon has failed!
Homebrew Bundle failed! 2 Brewfile dependencies failed to install.

**Comment by jasonrudolph** [comment]
:wave: @capnahab: Thanks for reporting this issue. I haven't upgraded to Big Sur yet, so I'm not sure which aspects of jasonrudolph/keyboard will work and which aspects won't work.

The `script/setup` and `Brewfile` are intended as a nice-to-have bit of automation, but if they're not working on Big Sur, can you try installing [karabiner-elements](https://karabiner-elements.pqrs.org/) and [hammerspoon](https://github.com/Hammerspoon/hammerspoon/releases) manually?

**Comment by capnahab** [comment]
Thank you, - I get the same message if I have manually preinstalled Hammerspoon and Karabiner.

brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
Error: Cask 'karabiner-elements' is unavailable: No Cask with this name exists.
Installing karabiner-elements has failed!
Error: Cask 'hammerspoon' is unavailable: No Cask with this name exists.
Installing hammerspoon has failed!
Homebrew Bundle failed! 2 Brewfile dependencies failed to install.

**Comment by capnahab** [comment]
I wonder if this is something to do with using Rosetta for brew. 
I tried <brew install karabiner-elements> , werent found.

brew install karabiner-elements
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "karabiner-elements".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by jasonrudolph** [comment]
> Thank you, - I get the same message if I have manually preinstalled Hammerspoon and Karabiner.

Sorry, @capnahab. I should have been more specific in my suggestion. Once you've installed Hammerspoon and Karabiner manually, you don't need homebrew for any other steps. I recommend commenting out this line and running `./script/setup` again:

https://github.com/jasonrudolph/keyboard/blob/a11a087dfd7639dccbcc2c0049da2ab2f41a1e71/script/setup#L7

Can you give that a try?

**Comment by capnahab** [comment]
Sorry Jason, 
I tried that and 
❯ script/setup
ln: /Users/np/.config//karabiner: Operation not permitted

**Comment by jasonrudolph** [comment]
👋 @capnahab: Thanks for giving that a try. It sounds like now you're running into the issue seen in https://github.com/jasonrudolph/keyboard/issues/67. I haven't been able to reproduce that issue, but some people have reported that they can work around it by removing the trailing slash on this line:

https://github.com/jasonrudolph/keyboard/blob/a11a087dfd7639dccbcc2c0049da2ab2f41a1e71/script/setup#L12

```diff
- ln -sfn $PWD/karabiner ~/.config/
+ ln -sfn $PWD/karabiner ~/.config
```

Can you try making that change and then running `./script/setup` again?

**Comment by capnahab** [comment]
Hi Jason, I suspect you are under the impression I know what I am doing here :),  ( I am a surgeon in my dayjob in the Uk). 
I changed the line above, but no joy so I looked in ~/.config and found karabiner so I renamed that karabiner_old and reran the script, - and it worked as normal. 
Thanks for your excellent help and dedication to this great project !.
n

**Comment by jasonrudolph** [comment]
Glad to hear that you were able to get things working, @capnahab! 🙌
