### ISSUE TITLE
Super Duper mode "space to select" is not working with "h" key 

### ISSUE THREAD

**Issue by garrofederico** [jasonrudolph/keyboard#81]
When I'm pressing (s)+(d) and holding (space) to select text, it only works when moving forward (pressing (l) key) and not when moving backwards (pressing (h). So that means I cannot select the text that is before the cursor.

So to sum up, the key combination (s)+(d)+(space)+(h) is not working for me

**Comment by jasonrudolph** [comment]
I wonder if you're running into the keyboard ghosting issue reported by @sullevy in #24.

Would you mind taking a look at [#24 (comment)](https://github.com/jasonrudolph/keyboard/issues/24#issuecomment-301804764) and letting me know if it explains the behavior you're seeing?

**Comment by brandonkboswell** [comment]
@jasonrudolph I was running into the same thing and it indeed appears to be the ghosting issue.

**Comment by garrofederico** [comment]
Indeed, this is the issue that I'm having. I'm using a 2018 Macbook pro with Touchbar and is not working, but when I use an external keyboard, I don't have the ghosting issue any more.

Many thanks for your answer!
