### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by cyrilgmathew** [jasonrudolph/keyboard#82]
Dear Jason,

I've been trying to install your keyboard on my Mac but when the bits are copied to the terminal the following error pops up:

fatal: destination path '/Users/cyril/.keyboard' already exists and is not an empty directory.
Homebrew is required: http://brew.sh/

Does this mean the keyboard is already installed? If so I would like to know if there are any additional steps to the installation because I am not able to use it's features presently.

Thanks
Cyril

**Comment by jasonrudolph** [comment]
👋 Hi @cyrilgmathew: I haven't seen this error before, but I'll try to help.

> fatal: destination path '/Users/cyril/.keyboard' already exists and is not an empty directory.

That's a strange error. The [setup script](https://github.com/jasonrudolph/keyboard/blob/e5e351f1cc80f62cca2ce688a5d4a3dd7f3a4b36/script/setup) doesn't do anything with a `.keyboard` directory. 🤔

> Homebrew is required: http://brew.sh/

This is probably the first thing we should look into. If you're seeing this output, then that likely means that Homebrew isn't installed. So, you'll need to install Homebrew first. 

Would you mind installing Homebrew and then retry installing jasonrudolph/keyboard?
