### ISSUE TITLE
Which key or key combination implements the CAPS function

### ISSUE THREAD

**Issue by waynez** [jasonrudolph/keyboard#83]
Hi,

With the CAPS key being mapped to left CTRL, which key or key combination can I use for the CAPS. I do need it from time to time.

Thanks

**Comment by jasonrudolph** [comment]
:wave: @waynez: I think you can implement something like this using Karabiner-Elements. For example, https://github.com/pqrs-org/Karabiner-Elements/issues/346#issuecomment-463258397 describes a configuration for double-tapping <kbd>shift</kbd> to enable caps lock.

I don't personally find myself wanting to enable caps lock, so it's unlikely that I'd add this to jasonrudolph/keyboard, but I hope the pointer above is helpful.

**Comment by waynez** [comment]
Thanks @jasonrudolph for the pointer! It does sound inspiring.
